{{- if .Values.analytics.enabled }}
{{- $fullName := printf "%s-storage-access" .Release.Name -}}
apiVersion: v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  namespace: default
spec:
  replicas: 0
  volumes:
  - name: "{{ .Release.Name }}-analyzer-data"
    persistentVolumeClaim:
      claimName: {{ .Release.Name }}-analyzer-data
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: {{ $fullName }}
    volumeMounts:
    - mountPath: /workspace/ProgressAnalysis
      name: "{{ .Release.Name }}-analyzer-data"
      subPath: analysis
  restartPolicy: Always